pack: bgpfilterupdate
enabled: true
runner_type: orquesta
name: uploadconfig
entry_point: workflows/uploadconfig.yaml
description: Upload config to router imposing random delays
parameters:
  files:
    type: string
    description: Path where the configuration file exists
    required: true
